"""Visualize statistics for cross features generated by the feature extractor."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import Config
from src.features import FeatureConfig, SimpleFeatureExtractor


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=str, required=True, help="Path to the YAML config file.")
    parser.add_argument(
        "--max-plots",
        type=int,
        default=12,
        help="Maximum number of cross features to plot histograms for.",
    )
    return parser.parse_args()


def build_feature_extractor(feature_cfg: Dict[str, object], cv_cfg: Dict[str, object]) -> FeatureConfig:
    """Construct FeatureConfig from dicts."""
    return FeatureConfig(
        drop_columns=feature_cfg.get("drop_columns", []),
        imputation_strategy=feature_cfg.get("imputation_strategy", "median"),
        scale=False,  # keep raw scale for interpretability in plots
        rolling_windows=feature_cfg.get("rolling_windows"),
        rolling_feature_naming=feature_cfg.get("rolling_feature_naming", "roll"),
        enable_interactions=feature_cfg.get("enable_interactions", True),
        time_column=cv_cfg.get("time_column"),
        group_column=cv_cfg.get("group_column"),
        missing_ratio_threshold=feature_cfg.get("missing_ratio_threshold", 40.0),
        manual_features=feature_cfg.get("manual_features"),
    )


def detect_cross_columns(df: pd.DataFrame) -> List[str]:
    """Identify cross features by name pattern produced by the extractor."""
    return [c for c in df.columns if "_x_" in c or "_div_" in c]


def plot_histograms(df: pd.DataFrame, cols: List[str], out_path: Path) -> None:
    """Plot histograms for selected columns."""
    n = len(cols)
    if n == 0:
        return
    n_cols = min(3, n)
    n_rows = int(np.ceil(n / n_cols))
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(4 * n_cols, 3 * n_rows))
    axes = axes.flatten() if isinstance(axes, np.ndarray) else [axes]
    for ax, col in zip(axes, cols):
        ax.hist(df[col].dropna(), bins=40, alpha=0.8)
        ax.set_title(col)
    for ax in axes[n:]:
        ax.axis("off")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_missing_ratio(df: pd.DataFrame, cols: List[str], out_path: Path) -> None:
    """Bar plot of missing ratios."""
    miss = df[cols].isna().mean().sort_values(ascending=False)
    fig, ax = plt.subplots(figsize=(10, 4))
    miss.plot(kind="bar", ax=ax)
    ax.set_ylabel("Missing ratio")
    ax.set_title("Cross feature missing ratio")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    config = Config.from_yaml(args.config)
    config.ensure_dirs()

    paths = config.get("paths")
    files = config.get("files")
    cv_cfg = config.get("cv")
    feature_cfg = config.get("features")

    train_df = pd.read_csv(Path(paths["input_dir"]) / files["train"])

    feature_config = build_feature_extractor(feature_cfg, cv_cfg)
    extractor = SimpleFeatureExtractor(feature_config)
    features = extractor.fit_transform(train_df, target_column=config.get("target")["column"])

    cross_cols = detect_cross_columns(features)
    if not cross_cols:
        print("No cross features detected (names containing '_x_' or '_div_').")
        return

    reports_dir = Path(paths.get("reports_dir", "reports"))
    reports_dir.mkdir(parents=True, exist_ok=True)

    # Stats table
    stats = features[cross_cols].describe(percentiles=[0.01, 0.05, 0.5, 0.95, 0.99]).T
    stats_path = reports_dir / "cross_feature_stats.csv"
    stats.to_csv(stats_path)

    # Missing ratio plot
    miss_plot_path = reports_dir / "cross_feature_missing_ratio.png"
    plot_missing_ratio(features, cross_cols, miss_plot_path)

    # Histograms for top-N columns by variance
    var_ranked = features[cross_cols].var().sort_values(ascending=False)
    top_cols = list(var_ranked.head(args.max_plots).index)
    hist_path = reports_dir / "cross_feature_histograms.png"
    plot_histograms(features, top_cols, hist_path)

    print("Saved cross feature summaries:")
    print(f"- stats: {stats_path}")
    print(f"- missing ratio plot: {miss_plot_path}")
    print(f"- histograms (top {len(top_cols)} by variance): {hist_path}")


if __name__ == "__main__":
    main()
